### ISSUE TITLE
POMDPXFile vs. POMDPXFiles

### ISSUE THREAD

**Issue by tawheeler** [JuliaPOMDP/POMDPXFiles.jl#4]
Two things:
1 - we have a `POMDPX` type for which the corresponding `POMDP` type for .pomdp files doesn't work. Suggest using `POMDPXFile`, `MOMDPXFile`, and `POMDPFile` instead

2 - this would lead us to having to rename the module to POMDPXFiles

**Comment by mykelk** [comment]
I agree.

**Comment by zsunberg** [comment]
I agree, this change would be in line with the package naming guidelines http://docs.julialang.org/en/release-0.4/manual/packages/#guidelines-for-naming-a-package

**Comment by mykelk** [comment]
Let's do it.

**Comment by etotheipluspi** [comment]
Name changes implemented!
